#  Use the official Nginx image as our base
FROM nginx:alpine

# Copy all your HTML, CSS, and JS files into the Nginx public HTML directory
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]